[package]
name = "demo_wasm"
version = "1.0.0-pre.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# a few minor fixes from https://github.com/hi-ogawa/OxiSynth/pull/1
oxisynth = { git = "https://github.com/hi-ogawa/OxiSynth", branch = "chore-realtime-safe" }
wasm-bindgen = { version = "0.2.83" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.4"
