[package]
name = "demo_wasm"
version = "1.0.0-pre.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = []
export_json_schema = []

[dependencies]
# a few minor fixes from https://github.com/hi-ogawa/OxiSynth/pull/1
oxisynth = { git = "https://github.com/hi-ogawa/OxiSynth", branch = "chore-realtime-safe" }
wasm-bindgen = { version = "0.2.83" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.4"
schemars = "0.8.11"
gloo-utils = "0.1.6"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
# https://rustwasm.github.io/docs/wasm-bindgen/examples/console-log.html
web-sys = { version = "0.3.60", features = ['console'] }
